### ISSUE TITLE
Add lessons to IMLS Official Website

### ISSUE THREAD

**Issue by lawtlee** [ucla-imls-open-sci/ucla-imls-open-sci.github.io#33]
We need to update the lessons in our IMLS official website. We lost the the lesson tables from last year. Could you help add two tables, one is for last year and one is for this year?

**Comment by cocoa-huang** [comment]
On it.

**Comment by lawtlee** [comment]
@cocoa-huang here is the list of the lessons
https://docs.google.com/spreadsheets/d/1Cw9PjTl0Z9KPIcnY3Od4CpOAkZO-rKJGz85LL3wUy3E/edit?gid=0#gid=0
we want to create a backlink to the one last year as well. You can reference the committee and do the same, if not then i can go in and do that and you can add it to our readme on our github
